Issue #SB-0000 fix: Updated Angular library 10 to 11
Sunbird-Ed/sb-content-module pull request #6
Opened 2022-11-25 12:13 UTC by princegupta1131

2022-11-25 12:20 UTC, rajeshkumaravel requested changes

2022-11-25 12:20 UTC, rajeshkumaravel commented on projects/content-section/package.json
> +    "@project-sunbird/common-consumption": ">= 4.12.0",
remove cap versioning

2022-11-25 12:20 UTC, rajeshkumaravel approved these changes

2022-11-28 05:04 UTC, rajeevsathish approved these changes

2022-11-28 05:04 UTC, merged